# .circleci/config.yml
version: 2.1
jobs:
  build-and-test_all:
    macos:
      xcode: 14.2.0
    steps:
      - run: brew install vapor
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane ios tests_app
      - run:
          name: Fastlane
          command: bundle exec fastlane ios tests_core
      - run:
          name: Fastlane
          command: bundle exec fastlane mac tests_server
      - run:
          name: Fastlane
          command: bundle exec fastlane mac test_integration
      - run:
          name: Fastlane
          command: bundle exec fastlane mac tests_mac_app
      - run:
          name: Fastlane
          command: bundle exec fastlane mac tests_mac_core

workflows:
  build-test:
    jobs:
      - build-and-test_all
