# .circleci/config.yml
version: 2.1
jobs:
  build-and-test_all:
    macos:
      xcode: 14.1.0
    steps:
      - run: brew install vapor
      - checkout
      - run: bundle install
      - run:
          name: Fastlane iOS test application
          command: bundle exec fastlane ios tests_app
      - run:
          name: Fastlane iOS test WalletCore
          command: bundle exec fastlane ios tests_core
      - run:
          name: Fastlane macOS test server
          command: bundle exec fastlane mac tests_server
      - run:
          name: Fastlane macOS test integration
          command: bundle exec fastlane mac test_integration
      - run:
          name: Fastlane mac test application
          command: bundle exec fastlane mac tests_mac_app
      - run:
          name: Fastlane mac test WalletCore
          command: bundle exec fastlane mac tests_mac_core

workflows:
  build-test:
    jobs:
      - build-and-test_all
