# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do
    setup_circle_ci
    unlock_keychain
  end

  desc "Builds and tests iOS app"
  lane :tests_app do
    run_tests(
      project: "Wallet.xcodeproj",
      devices: ["iPhone 14"],
      scheme: "Wallet (iOS)"
    )
  end
  
  desc "Builds and tests WalletCore"
  lane :tests_core do
    sh("xcodebuild -project \"../Wallet.xcodeproj\" -scheme \"WalletCoreTests\" test")
  end
  
      

end

platform :mac do

  before_all do
    setup_circle_ci
    unlock_keychain
  end

  desc "Builds server and run unit tests"
  lane :tests_server do
    sh("cd ..")
    sh("xcodebuild -project \"../Wallet.xcodeproj\" -scheme \"AppTests\" test")
  end
  
  desc "bulds Core library and does integration tests app"
  lane :test_integration do
      sh("xcodebuild -project \"../Wallet.xcodeproj\" -scheme \"WalletCoreIntegrationTests\" test")
  end
  
  desc "Builds and tests Mac app"
  lane :tests_mac_app do
    run_tests(
      project: "Wallet.xcodeproj",
      scheme: "Wallet Mac"
    )
  end

end
